fixtures:
  repositories:
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
    php: "git://github.com/jippi/puppet-php.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    zabbix: "#{source_dir}"
