name          'shoekstra-zabbix'
version       '0.1.0'
source        'https://github.com/shoekstra/puppet-zabbix.git'
author        'Stephen Hoekstra'
license       'Apache License, Version 2.0'
summary       'Puppet module to install and configure Zabbix agents, frontends, proxies and servers.'
description   'This module installs and configures each Zabbix component.'
project_page  'https://github.com/shoekstra/puppet-zabbix'

dependency 'nodes/php'
dependency 'puppetlabs/apache'
dependency 'puppetlabs/apt'
dependency 'puppetlabs/concat'
dependency 'puppetlabs/inifile'
dependency 'puppetlabs/mysql'
dependency 'puppetlabs/stdlib'
